defaults:
  - model: ContrastiveModel
  - datamodule: GeneToken
  - split: split_v1_large
  - _self_

wandb:
  enabled: True
  run_id: null
  run_name: ???
  entity: theislab-transformer
  project: contrastive-transformer

initialize:  
  resume: False
  run_id: null
  checkpoint: null
  
PATH:
  PROJECT_PATH: ???
  PROJECT_DATA_PATH: ${PATH.PROJECT_PATH}/data
  CHECKPOINT_ROOT: ${PATH.PROJECT_PATH}/model_checkpoints
  DATASET_PATH: ${PATH.PROJECT_DATA_PATH}/cxg_raw_2023-12-15
  ADATA_PATH: ${PATH.DATASET_PATH}/h5ads
  PANELS_PATH: ${PATH.PROJECT_PATH}/panels/human
  SPLIT: ${split}
  gene_mapping_path: ${PATH.DATASET_PATH}/pc_gene_token_mapping.pkl



# Project directory structure:
# PROJECT_PATH/
# ├── data/
# │   └── <dataset_name>/
# │       ├── pc_gene_token_mapping.pkl
# │       └── h5ads/
# │           ├── <adata_1>.h5ad
# │           ├── <adata_2>.h5ad
# │           └── ...
# ├── model_checkpoints/
# └── panels/
#     └── <panel_name>/
#         ├── panel_1.csv
#         ├── panel_2.csv
#         └── ...
